export const WS_MSG = {
	TICKETS_CREATED: 'MSG_TICKETS_CREATED',
	TICKETS_UPDATED: 'MSG_TICKETS_UPDATED',
	SYSTEM_ENABLED: 'SYSTEM_ENABLED',
	SYSTEM_DISABLED: 'SYSTEM_DISABLED'
}

export const TICKET_STATUS = {
	CANCELLED: 0,
	PENDING: 1,
	SERVING: 2,
	SERVED: 3
}

export const SYSTEM_STATUS = {
	DISABLED: 0,
	ENABLED: 1
}

export const KEYS = {
	SYSTEM_STATUS: 'system_status'
}
